### ISSUE TITLE
Given Settings object is not a valid JSON : with mask-inputs as true

### ISSUE THREAD

**Issue by kanika1894** [Azure/appservice-settings#20]
Post the commit : https://github.com/Azure/appservice-settings/commit/e73fc9b93c4f6c45637bd4d58a7bfed3aa790d79, the existing workflows using this action have started failing, with the error that the given settings is not a Valid JSON.
Sample run : https://github.com/ddivanshu/acr-build-helloworld-node/runs/1485157702?check_suite_focus=true

Though the hack is to work by setting the value to false which enables the workflow. (https://github.com/ddivanshu/acr-build-helloworld-node/runs/1412786294?check_suite_focus=true)
But this means all the workflow files using this action need to be updated.
A hotfix for this is required as soon as possible as it is a live site issue

**Comment by aksm-ms** [comment]
@kanika1894 Issue is fixed in PR. Please check and let me know.

**Comment by kanika1894** [comment]
Thanks for the fix.
