### ISSUE TITLE
How to use Environment Variables from Azure during the build?

### ISSUE THREAD

**Issue by cfofiu** [Azure/appservice-settings#25]
So, I have a simple, I'm sure very common use case:

I have these environment variables in Azure App Service and I want to use them to build my code.

<img width="663" alt="Screen Shot 2021-04-29 at 6 20 09 PM" src="https://user-images.githubusercontent.com/2437645/116625395-8a9fc300-a917-11eb-97b5-39e51b3cb2a9.png">

They are used like this in the code:
```
process.env.NEXT_PUBLIC_DISPLAY_ENV
```

I can't find it clear in the documentation and I am lost on how to do it?!? Can you please help/explain/update the documentation?

Thanks!

**Comment by kanika1894** [comment]
Hey @cfofiu 
This action is only to configure/write the settings and not "get"/"read" the existing settings and use them in workflow configuration. So the requirement you mentioned is not supported.
