### ISSUE TITLE
Variable in appsettings json

### ISSUE THREAD

**Issue by olaj** [Azure/appservice-settings#6]
I'm trying to figure out how to use a variable in my appsettings json. The example in the docs you guys use a secret but i want to set the build number as a appsetting and i can't get it to work. Tried all sorts of expressions and stuff.

`          app-settings-json: >
            [
            {
              "name": "DEPLOY_ENV",
              "value": "beta",
              "slotSetting": true
            },
            {
              "name": "NODE_ENV",
              "value": "production",
              "slotSetting": true
            },
            {
              "name": "WEBSITE_NODE_DEFAULT_VERSION",
              "value": "10.6.0",
              "slotSetting": false
            },
            {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "1",
              "slotSetting": false
            },
            {
              "name": "BUILD_NO",
              "value": "${{BUILD_NUMBER}}",
              "slotSetting": false
            }
]`

              "value": "$BUILD_NUMBER"

              "value": {{BUILD_NUMBER}}

              "value": {{$BUILD_NUMBER}}

And so on, nothing seems to work. Everything else work though, i just can't manage to "inject" a dynamic value into the json.

**Comment by olaj** [comment]
Is anyone looking here at all?

**Comment by eaarora-ms** [comment]
@olaj We are extremely sorry for the delay in reply. If you want to use variables in your pipeline you can follow a similar way as used in yaml. 
"value" : $(BUILD_NUMBER)

Please refer: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax
Please let us know if there is any other help required.
